language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - linux

branches:
  only:
    - "master"

cache:
    apt: true
    directories:
        - $HOME/.runtimes
        - $HOME/.venv
        - $HOME/.cache/pip
        - $HOME/wheelhouse
        - $HOME/.stack
        - $HOME/.local

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - FORMAT_ALL=true

jobs:
  include:
    # Prechecks that we want to run first.
    - stage: precheck
      env: TASK=check-whole-repo-tests
    - env: TASK=lint-ruby

script:
    - ./build.sh

matrix:
    fast_finish: true

notifications:
  email:
    recipients:
      - david@drmaciver.com
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - libgmp-dev
